// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLKhoaHoc_API.DataContext;

#nullable disable

namespace QLKhoaHocAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLKhoaHoc_API.Entities.BaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChuDeId")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungNgan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("TenBaiViet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTacGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianTao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChuDeId");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("BaiViet_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.ChuDe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("LoaiBaiVietId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenChuDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LoaiBaiVietId");

                    b.ToTable("ChuDe_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.DangKyHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HocVIenId")
                        .HasColumnType("int");

                    b.Property<int?>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<int?>("TinhTrangHocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HocVIenId");

                    b.HasIndex("KhoaHocId");

                    b.HasIndex("TaiKhoanId");

                    b.HasIndex("TinhTrangHocId");

                    b.ToTable("DangKyHoc_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.HocVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongXa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuanHuyen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoNha")
                        .HasColumnType("int");

                    b.Property<string>("TinhThanh")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HocVien_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.KhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GioiThieu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HocPhi")
                        .HasColumnType("float");

                    b.Property<int?>("LoaiKhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoHocVien")
                        .HasColumnType("int");

                    b.Property<int?>("SoLuongMon")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoaHoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ThoiGianHoc")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiKhoaHocId");

                    b.ToTable("KhoaHoc_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.LoaiBaiViet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiBaiViet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiBaiViet_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.LoaiKhoaHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenLoaiKhoaHoc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoaiKhoaHoc_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.QuyenHan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenQuyenHan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("QuyenHan_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiredTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaiKhoanId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TaiKhoanId");

                    b.ToTable("RefreshToken_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.TaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuyenHanId")
                        .HasColumnType("int");

                    b.Property<string>("TajKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNguoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuyenHanId");

                    b.ToTable("TaiKhoan_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.TinhTrangHoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenTinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TinhTrangHoc_tbl");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.BaiViet", b =>
                {
                    b.HasOne("QLKhoaHoc_API.Entities.ChuDe", "ChuDe")
                        .WithMany("baiViets")
                        .HasForeignKey("ChuDeId");

                    b.HasOne("QLKhoaHoc_API.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("baiViets")
                        .HasForeignKey("TaiKhoanId");

                    b.Navigation("ChuDe");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.ChuDe", b =>
                {
                    b.HasOne("QLKhoaHoc_API.Entities.LoaiBaiViet", "LoaiBaiViet")
                        .WithMany("chuDes")
                        .HasForeignKey("LoaiBaiVietId");

                    b.Navigation("LoaiBaiViet");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.DangKyHoc", b =>
                {
                    b.HasOne("QLKhoaHoc_API.Entities.HocVien", "HocVien")
                        .WithMany("dangKyHocs")
                        .HasForeignKey("HocVIenId");

                    b.HasOne("QLKhoaHoc_API.Entities.KhoaHoc", "KhoaHoc")
                        .WithMany("dangKyHocs")
                        .HasForeignKey("KhoaHocId");

                    b.HasOne("QLKhoaHoc_API.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany("dangKyHocs")
                        .HasForeignKey("TaiKhoanId");

                    b.HasOne("QLKhoaHoc_API.Entities.TinhTrangHoc", "TinhTrangHoc")
                        .WithMany("dangKyHocs")
                        .HasForeignKey("TinhTrangHocId");

                    b.Navigation("HocVien");

                    b.Navigation("KhoaHoc");

                    b.Navigation("TaiKhoan");

                    b.Navigation("TinhTrangHoc");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.KhoaHoc", b =>
                {
                    b.HasOne("QLKhoaHoc_API.Entities.LoaiKhoaHoc", "LoaiKhoaHoc")
                        .WithMany("khoaHocs")
                        .HasForeignKey("LoaiKhoaHocId");

                    b.Navigation("LoaiKhoaHoc");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.RefreshToken", b =>
                {
                    b.HasOne("QLKhoaHoc_API.Entities.TaiKhoan", "TaiKhoan")
                        .WithMany()
                        .HasForeignKey("TaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.TaiKhoan", b =>
                {
                    b.HasOne("QLKhoaHoc_API.Entities.QuyenHan", "QuyenHan")
                        .WithMany("taiKhoans")
                        .HasForeignKey("QuyenHanId");

                    b.Navigation("QuyenHan");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.ChuDe", b =>
                {
                    b.Navigation("baiViets");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.HocVien", b =>
                {
                    b.Navigation("dangKyHocs");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.KhoaHoc", b =>
                {
                    b.Navigation("dangKyHocs");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.LoaiBaiViet", b =>
                {
                    b.Navigation("chuDes");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.LoaiKhoaHoc", b =>
                {
                    b.Navigation("khoaHocs");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.QuyenHan", b =>
                {
                    b.Navigation("taiKhoans");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.TaiKhoan", b =>
                {
                    b.Navigation("baiViets");

                    b.Navigation("dangKyHocs");
                });

            modelBuilder.Entity("QLKhoaHoc_API.Entities.TinhTrangHoc", b =>
                {
                    b.Navigation("dangKyHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
